app/Http/routes.php
<?php

// See: https://laravel-china.org/topics/2484#reply2

// Everything is moved to `routes` folder in the root.

routes/web.php
<?php
# ------------------ Page Route ------------------------
Route::get('/', 'PagesController@home')->name('home');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/search', 'PagesController@search')->name('search');
Route::get('/feed', 'PagesController@feed')->name('feed');
Route::get('/wiki', 'PagesController@wiki')->name('wiki');
Route::get('/sitemap', 'PagesController@sitemap');
Route::get('/sitemap.xml', 'PagesController@sitemap');
Route::get('/hall_of_fames', 'PagesController@hallOfFames')->name('hall_of_fames');
Route::get('/composer', 'PagesController@composer')->name('composer');

Route::get('/roles/{id}', 'RolesController@show')->name('roles.show');

# ------------------ User stuff ------------------------

Route::get('/users/drafts', 'UsersController@drafts')->name('users.drafts');
Route::get('/users/{id}/replies', 'UsersController@replies')->name('users.replies');
Route::get('/users/{id}/topics', 'UsersController@topics')->name('users.topics');
Route::get('/users/{id}/articles', 'UsersController@articles')->name('users.articles');
Route::get('/users/{id}/votes', 'UsersController@votes')->name('users.votes');
Route::get('/users/{id}/following', 'UsersController@following')->name('users.following');
Route::get('/users/{id}/followers', 'UsersController@followers')->name('users.followers');

Route::get('/users/{id}/refresh_cache', 'UsersController@refreshCache')->name('users.refresh_cache');
Route::get('/users/{id}/access_tokens', 'UsersController@accessTokens')->name('users.access_tokens');
Route::get('/access_token/{token}/revoke', 'UsersController@revokeAccessToken')->name('users.access_tokens.revoke');
Route::post('/users/regenerate_login_token', 'UsersController@regenerateLoginToken')->name('users.regenerate_login_token');

Route::post('/users/follow/{id}', 'UsersController@doFollow')->name('users.doFollow');
Route::get('/users/{id}/edit_email_notify', 'UsersController@editEmailNotify')->name('users.edit_email_notify');
Route::post('/users/{id}/update_email_notify', 'UsersController@updateEmailNotify')->name('users.update_email_notify');
Route::get('/users/{id}/edit_password', 'UsersController@editPassword')->name('users.edit_password');
Route::patch('/users/{id}/update_password', 'UsersController@updatePassword')->name('users.update_password');
Route::get('/users/{id}/edit_social_binding', 'UsersController@editSocialBinding')->name('users.edit_social_binding');

Route::get('/users', 'UsersController@index')->name('users.index');
Route::get('/users/create', 'UsersController@create')->name('users.create');
Route::post('/users', 'UsersController@store')->name('users.store');
Route::get('/users/{id}', 'UsersController@show')->name('users.show');
Route::get('/users/{id}/edit', 'UsersController@edit')->name('users.edit');
Route::patch('/users/{id}', 'UsersController@update')->name('users.update');
Route::get('/users/{id}/edit_avatar', 'UsersController@editAvatar')->name('users.edit_avatar');
Route::patch('/users/{id}/update_avatar', 'UsersController@updateAvatar')->name('users.update_avatar');

Route::get('/notifications/unread', 'NotificationsController@unread')->name('notifications.unread');
Route::get('/notifications', 'NotificationsController@index')->name('notifications.index');
Route::get('/notifications/count', 'NotificationsController@count')->name('notifications.count');

Route::get('/messages', 'MessagesController@index')->name('messages.index');
Route::get('/messages/to/{id}', 'MessagesController@create')->name('messages.create');
Route::post('/messages', 'MessagesController@store')->name('messages.store');
Route::get('/messages/{id}', 'MessagesController@show')->name('messages.show');
Route::put('/messages/{id}', 'MessagesController@update')->name('messages.update');

Route::get('/email-verification-required', 'UsersController@emailVerificationRequired')->name('email-verification-required');
Route::post('/users/send-verification-mail', 'UsersController@sendVerificationMail')->name('users.send-verification-mail');

# ------------------ Authentication ------------------------

Route::get('/login', 'Auth\AuthController@oauth')->name('login');
Route::get('/auth/login', 'Auth\AuthController@signin')->name('auth.login');
Route::post('/auth/login', 'Auth\AuthController@postLogin')->name('auth.login');
Route::get('/login-required', 'Auth\AuthController@loginRequired')->name('login-required');
Route::get('/admin-required', 'Auth\AuthController@adminRequired')->name('admin-required');
Route::get('/user-banned', 'Auth\AuthController@userBanned')->name('user-banned');
Route::get('/signup', 'Auth\AuthController@create')->name('signup');
Route::post('/signup', 'Auth\AuthController@createNewUser')->name('signup');
Route::get('/logout', 'Auth\AuthController@logout')->name('logout');
Route::get('/oauth', 'Auth\AuthController@getOauth');

Route::get('/auth/oauth', 'Auth\AuthController@oauth')->name('auth.oauth');
Route::get('/auth/callback', 'Auth\AuthController@callback')->name('auth.callback');
Route::get('/verification/{token}', 'Auth\AuthController@getVerification')->name('verification');

# ------------------ Categories ------------------------

Route::get('categories/{id}', 'CategoriesController@show')->name('categories.show');

# ------------------ Site ------------------------

Route::get('/sites', 'SitesController@index')->name('sites.index');

# ------------------ Replies ------------------------

Route::post('/replies', 'RepliesController@store')->name('replies.store')->middleware('verified_email');
Route::delete('replies/delete/{id}', 'RepliesController@destroy')->name('replies.destroy')->middleware('auth');

# ------------------ Topic ------------------------
Route::get('/topics', 'TopicsController@index')->name('topics.index');
Route::get('/topics/create', 'TopicsController@create')->name('topics.create')->middleware('verified_email');
Route::post('/topics', 'TopicsController@store')->name('topics.store')->middleware('verified_email');
Route::get('/topics/{id}/edit', 'TopicsController@edit')->name('topics.edit');
Route::patch('/topics/{id}', 'TopicsController@update')->name('topics.update');
Route::delete('/topics/{id}', 'TopicsController@destroy')->name('topics.destroy');
Route::post('/topics/{id}/append', 'TopicsController@append')->name('topics.append');

# ------------------ User Topic Actions ------------------------

Route::group(['before' => 'auth'], function () {
    Route::post('/topics/{id}/upvote', 'TopicsController@upvote')->name('topics.upvote');
    Route::post('/topics/{id}/downvote', 'TopicsController@downvote')->name('topics.downvote');
    Route::post('/replies/{id}/vote', 'RepliesController@vote')->name('replies.vote');
    Route::post('/attentions/{id}', 'AttentionsController@createOrDelete')->name('attentions.createOrDelete');
});

# ------------------ Admin Route ------------------------

Route::group(['before' => 'manage_topics'], function () {
    Route::post('topics/recommend/{id}', 'TopicsController@recommend')->name('topics.recommend');
    Route::post('topics/pin/{id}', 'TopicsController@pin')->name('topics.pin');
    Route::delete('topics/delete/{id}', 'TopicsController@destroy')->name('topics.destroy');
    Route::post('topics/sink/{id}', 'TopicsController@sink')->name('topics.sink');
});

Route::group(['before' => 'manage_users'], function () {
    Route::post('users/blocking/{id}', 'UsersController@blocking')->name('users.blocking');
});

Route::post('/upload_image', 'TopicsController@uploadImage')->name('upload_image')->middleware('auth');

// Health Checking
Route::get('heartbeat', function () {
    return Category::first();
});

Route::get('/github-api-proxy/users/{username}', 'UsersController@githubApiProxy')->name('users.github-api-proxy');
Route::group(['middleware' => ['auth', 'admin_auth']], function () {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

# ------------------ Blogs ------------------------

Route::get('/blogs', 'BlogsController@index')->name('blogs.index');
Route::get('/blogs/create', 'BlogsController@create')->name('blogs.create')->middleware('verified_email');
Route::post('/blogs', 'BlogsController@store')->name('blogs.store')->middleware('verified_email');
Route::get('/blogs/{id}/edit', 'BlogsController@edit')->name('blogs.edit');
Route::patch('/blogs/{id}', 'BlogsController@update')->name('blogs.update');

Route::post('/blogs/{blog}/subscribe', 'BlogsController@subscribe')->name('blogs.subscribe');
Route::post('/blogs/{blog}/unsubscribe', 'BlogsController@unsubscribe')->name('blogs.unsubscribe');

// Article
Route::get("/articles/create", "ArticlesController@create")->name('articles.create')->middleware('verified_email');
Route::patch("/topics/{id}/transform", "ArticlesController@transform")->name('articles.transform');
Route::post("/articles", "ArticlesController@store")->name('articles.store')->middleware('verified_email');
Route::get("/articles/{id}/edit", "ArticlesController@edit")->name('articles.edit');

Route::get('/topics/{id}/{slug?}', 'TopicsController@show')->name('topics.show');
Route::get('/articles/{id}/{slug?}', "TopicsController@show")->name('articles.show');

# ------------------ ShareLinks ------------------------

Route::get('/links/share', 'ShareLinksController@createLink')->name('share_links.create');
Route::get('/share_links/{id}/edit', 'ShareLinksController@edit')->name('share_links.edit');

# ------------------ Wild Card ------------------------

Route::get('{name}', 'PagesController@wildcard')->name('wildcard');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Laracasts\Presenter\PresentableTrait;
use Venturecraft\Revisionable\RevisionableTrait;
use Overtrue\LaravelFollow\FollowTrait;
use App\Jobs\SendActivateMail;
use Carbon\Carbon;
use Cache;
use Nicolaslopezj\Searchable\SearchableTrait;
use Cmgmyr\Messenger\Traits\Messagable;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract
{
    use Traits\UserRememberTokenHelper;
    use Traits\UserSocialiteHelper;
    use Traits\UserAvatarHelper;
    use Traits\UserActivityHelper;

    use Messagable;

    use PresentableTrait;
    public $presenter = 'Phphub\Presenters\UserPresenter';

    use SearchableTrait;
    protected $searchable = [
        'columns' => [
            'users.name' => 10,
            'users.real_name' => 10,
            'users.introduction' => 10,
        ],
    ];

    public function getAuthIdentifierName()
    {
        return 'id';
    }

    // For admin log
    use RevisionableTrait;
    protected $keepRevisionOf = [
        'is_banned'
    ];

    use EntrustUserTrait {
        restore as private restoreEntrust;
        EntrustUserTrait::can as may;
    }
    use SoftDeletes { restore as private restoreSoftDelete; }
    use FollowTrait;
    protected $dates = ['deleted_at'];

    protected $table   = 'users';
    protected $guarded = ['id', 'is_banned'];

    public static function boot()
    {
        parent::boot();

        static::created(function ($user) {
            $driver = $user['github_id'] ? 'github' : 'wechat';
            SiteStatus::newUser($driver);

            dispatch(new SendActivateMail($user));
        });

        static::deleted(function ($user) {
            \Artisan::call('phphub:clear-user-data', ['user_id' => $user->id]);
        });
    }

    public function scopeIsRole($query, $role)
    {
        return $query->whereHas('roles', function ($query) use ($role) {
                $query->where('name', $role);
            }
        );
    }

    public static function byRolesName($name)
    {
        $data = Cache::remember('phphub_roles_'.$name, 60, function () use ($name) {
            return User::isRole($name)->orderBy('last_actived_at', 'desc')->get();
        });
        return $data;
    }

    public function managedBlogs()
    {
        return $this->belongsToMany(Blog::class, 'blog_managers');
    }

    /**
     * For EntrustUserTrait and SoftDeletes conflict
     */
    public function restore()
    {
        $this->restoreEntrust();
        $this->restoreSoftDelete();
    }

    public function votedTopics()
    {
        return $this->morphedByMany(Topic::class, 'votable', 'votes')->withPivot('created_at');
    }

    public function topics()
    {
        return $this->hasMany(Topic::class);
    }

    public function blogs()
    {
        return $this->hasMany(Blog::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function subscribes()
    {
        return $this->belongsToMany(Blog::class, 'blog_subscribers');
    }

    public function attentTopics()
    {
        return $this->belongsToMany(Topic::class, 'attentions')->withTimestamps();
    }

    public function notifications()
    {
        return $this->hasMany(Notification::class)->recent()->with('topic', 'fromUser')->paginate(20);
    }

    public function revisions()
    {
        return $this->hasMany(Revision::class);
    }

    public function scopeRecent($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    public function getIntroductionAttribute($value)
    {
        return str_limit($value, 68);
    }

    public function getPersonalWebsiteAttribute($value)
    {
        return str_replace(['https://', 'http://'], '', $value);
    }

    public function isAttentedTopic(Topic $topic)
    {
        return Attention::isUserAttentedTopic($this, $topic);
    }

    public function subscribe(Blog $blog)
    {
        return $blog->subscribers()->where('user_id', $this->id)->count() > 0;
    }

    public function isAuthorOf($model)
    {
        return $this->id == $model->user_id;
    }

    /**
     * ----------------------------------------
     * UserInterface
     * ----------------------------------------
     */

    public function getAuthIdentifier()
    {
        return $this->getKey();
    }

    public function getAuthPassword()
    {
        return $this->password;
    }

    public function recordLastActivedAt()
    {
        $now = Carbon::now()->toDateTimeString();

        $update_key = config('phphub.actived_time_for_update');
        $update_data = Cache::get($update_key);
        $update_data[$this->id] = $now;
        Cache::forever($update_key, $update_data);

        $show_key = config('phphub.actived_time_data');
        $show_data = Cache::get($show_key);
        $show_data[$this->id] = $now;
        Cache::forever($show_key, $show_data);
    }
}

resources/views/pages/about.blade.php
@extends('layouts.default')

@section('title')
{{ lang('About Us') }}_@parent
@stop

@section('content')

    <div class="panel padding-lg rm-padding-top">
        <div class="panel-body">

        <div class="markdown-body" id="emojify">


<h1 id="toc_0">关于 Laravel China</h1>

<h2 id="toc_1">说明</h2>

<p>Laravel China 积极向上的 Laravel 和 PHP 开发者社区</p>
<p>我们致力于推动 Laravel, php-fig 等国外 PHP 新技术，新理念在中国的发展。</p>

<p>论坛基于开源项目 PHPHub，PHPHub 由 Laravel5.1 构建，<a href="https://github.com/summerblue/phphub5">源代码在此 at GitHub</a>。欢迎贡献代码，或者 <a href="https://github.com/summerblue/phphub5/issues">提交 Bug Report</a>。</p>

<h2 id="toc_2">关于新手问题</h2>

<p>这个社区不是用来问新手问题的，如果你是 PHP 新手，请先看 <a href="http://www.phptherightway.com/">PHP The Right Way</a>， 里面有中文版本，此文档能为你构建一个合理的 PHP 基础知识体系。</p>

<p>第一次接触 Laravel? 这里是  <a href="http://laravel-china.org/docs/home">Laravel 中文文档</a>，Laravel 的出名，也得益于这份撰写精炼的文档，值得多次品读。</p>

<p>在学习上遇到问题的时候，请先 Google。</p>

<p>如果觉得你的问题比较独占，请先仔细阅读 <a href="https://laravel-china.org/topics/535">提问的智慧</a>，然后在 <a href="https://laravel-china.org/categories/4">问答分类下</a> 发表你的问题，谢谢。 </p>

<h2 id="toc_3">愿景 Vision</h2>

<blockquote>
<p>下面是 laravel-china.org 创建的初衷，与君共勉。</p>
</blockquote>

<h3 id="toc_4">在这里的我们</h3>

<ul>
<li>热爱开源, 尊重开源;</li>
<li>热爱技术, 为最新最潮的技术狂热;</li>
<li>热爱学习, 热爱互联网;</li>
<li>热爱 PHP &amp; Laravel;</li>
</ul>

<h3 id="toc_5">在这里我们可以</h3>

<ul>
<li>分享生活见闻，分享知识，分享创意</li>
<li>接触新技术</li>
<li>为自己的创业项目找合伙人</li>
<li>讨论技术解决方案</li>
<li>自发线下聚会</li>
<li>遇见志同道合的人</li>
<li>发现更好工作机会</li>
<li>甚至是开始另一个神奇的开源项目</li>
<li>... </li>
</ul>

<h3 id="toc_6">在这里我们不可以</h3>

<ul>
<li>这里绝对不讨论任何有关盗版软件、音乐、电影如何获得的问题 </li>
<li>这里感激和崇尚美的事物 </li>
<li>这里尊重原创 </li>
<li>这里反对中文互联网上的无信息量习惯如“顶”，“沙发”，“前排”，“留名”，“路过” </li>
</ul>

<h2 id="toc_7">Laravel?</h2>

<p>为什么是 Laravel? 为什么不是 CI, Symfony, CakePHP, ThinkPHP ... </p>

<blockquote>
<p>Because Laravel is amazing and It is the future.</p>
</blockquote>

<p><a href="http://www.zhihu.com/question/19558755/answer/23062110">知乎上的答案 - 最好的 PHP 框架是什么？为什么？</a></p>

<p>需要补充的一句是, <code>绝不排斥</code> 别的框架的讨论, 只要是 <code>PHP</code> 相关技术讨论我们都欢迎。</p>



        </div>

        </div>
    </div>

@stop

resources/views/pages/hall_of_fame.blade.php
@extends('layouts.default')

@section('title')
Laravel China 名人堂 @parent
@stop

@section('content')

<div class="hall_of_fames">

    <div class="box text-center site-intro rm-link-color">
        Laravel China 名人堂，用于推荐对 Laravel China 社区有突出贡献的用户。<a style="text-decoration: underline;" href="https://laravel-china.org/topics/2440">更多信息</a>
    </div>

    @foreach($users as $index => $user)

        <div class="col-lg-6 ">

            <div class="card {{ $index % 2 == 0 ? 'add-margin-right' : 'add-margin-left' }}">

                @if ($currentUser && $currentUser->id == $user->id)
                <a class="pull-right popover-with-html text-lg animated rubberBand edit-btn" href="{{ route('users.edit', $user->id) }}" data-content="{{ lang('Edit Profile') }}">
                    <i class="fa fa-cog"></i>
                </a>
                @endif

              <div class="media-left">
                <a href="{{ route('users.show', $user->id) }}">
                  <img src="{{ $user->present()->gravatar }}" class="img-thumbnail avatar" />
                </a>
              </div>
              <div class="media-body padding-top-sm">
                <div class="media-heading">
                    <a href="{{ route('users.show', [$user->id]) }}" title="{{{ $user->name }}}" class="remove-padding-left author">
                        {{{ $user->name }}}
                    </a>
                    @if($user->introduction)
                    <span class="introduction">
                         ，{{{ $user->introduction }}}
                    </span>
                    @endif
                </div>

                <div class="certification">
                    {!! $user->certification !!}
                </div>

                <ul class="list-inline">

                  @if ($user->real_name)
                    <li class="popover-with-html" data-content="{{ lang('Real Name') }}"><span class="org"><i class="fa fa-user"></i> {{{ $user->real_name }}}</span></li>
                  @endif

                  @if ($user->github_name)
                  <li class="popover-with-html" data-content="{{ $user->github_name }}">
                    <a href="https://github.com/{{ $user->github_name }}" target="_blank">
                      <i class="fa fa-github-alt"></i>
                    </a>
                  </li>
                  @endif

                  @if ($user->weibo_link)
                  <li class="popover-with-html" data-content="{{ $user->weibo_name }}">
                    <a href="{{ $user->weibo_link }}" rel="nofollow" class="weibo" target="_blank"><i class="fa fa-weibo"></i>
                    </a>
                  </li>
                  @endif

                  @if ($user->twitter_account)
                  <li class="popover-with-html" data-content="{{ $user->twitter_account }}">
                    <a href="https://twitter.com/{{ $user->twitter_account }}" rel="nofollow" class="twitter" target="_blank"><i class="fa fa-twitter"></i>
                    </a>
                </li>
                  @endif

                  @if ($user->linkedin)
                  <li class="popover-with-html" data-content="点击查看 LinkedIn 个人资料">
                    <a href="{{ $user->linkedin }}" rel="nofollow" class="linkedin" target="_blank"><i class="fa fa-linkedin"></i>
                    </a>
                </li>
                  @endif

                  @if ($user->personal_website)
                  <li class="popover-with-html" data-content="{{ $user->personal_website }}">
                    <a href="http://{{ $user->personal_website }}" rel="nofollow" target="_blank" class="url">
                      <i class="fa fa-globe"></i>
                    </a>
                </li>
                  @endif

                @if ($user->company)
                  <li class="popover-with-html" data-content="{{ $user->company }}"><i class="fa fa-users"></i> </li>
                @endif

                @if ($user->city)
                  <li class="popover-with-html" data-content="{{ $user->city }}"><i class="fa fa-map-marker"></i> </li>
                @endif

              </ul>



                <div class="clearfix"></div>
              </div>
            </div>

        </div>

    @endforeach


    @include('layouts.partials.topbanner')
</div>

@stop

resources/views/pages/home.blade.php
@extends('layouts.default')

@section('content')

<div class="box text-center site-intro rm-link-color">
  {!! lang('site_intro') !!}
</div>

@include('layouts.partials.topbanner')

<div class="panel panel-default list-panel home-topic-list">
  <div class="panel-heading">
    <h3 class="panel-title text-center">
      {{ lang('Excellent Topics') }} &nbsp;
      <a href="{{ route('feed') }}" style="color: #E5974E; font-size: 14px;" target="_blank">
         <i class="fa fa-rss"></i>
      </a>
    </h3>

  </div>

  <div class="panel-body ">
	@include('pages.partials.topics')
  </div>

  <div class="panel-footer text-right">

  	<a href="topics?filter=excellent" class="more-excellent-topic-link">
  		{{ lang('More Excellent Topics') }} <i class="fa fa-arrow-right" aria-hidden="true"></i>
  	</a>
  </div>
</div>

@stop

resources/views/pages/search.blade.php
@extends('layouts.default')

@section('title')
{{ $query }} · 搜索结果 | @parent
@stop

@section('content')

<div class="panel panel-default list-panel search-results">
  <div class="panel-heading">

    @if ($filterd_noresult)
        <h3 class="panel-title ">
          <i class="fa fa-search"></i> 关键词 “{{ $query }}” 搜索范围：{{ $user->name }} <a class="popover-with-html" data-content="清除搜索范围" href="{{ route('search', ['q' => Input::get('q')]) }}"><i class="fa fa-times" aria-hidden="true"></i></a> 的结果为空。以下展示全局的搜索 {{ count($users) + $topics->total() }} 条：
        </h3>
    @else
        <h3 class="panel-title ">
         <i class="fa fa-search"></i> 关于 “{{ $query }}” 的搜索结果, 共 {{ count($users) + $topics->total() }} 条
          @if ($user->id > 0)
              。当前搜索范围：{{ $user->name }} <a class="popover-with-html" data-content="清除搜索范围" href="{{ route('search', ['q' => Input::get('q')]) }}"><i class="fa fa-times" aria-hidden="true"></i></a>
          @endif
        </h3>
    @endif

  </div>

  <div class="panel-body ">

        @if (count($users))
            @foreach ($users as $user_result)
                @include('pages.partials.users_result')
            @endforeach
        @endif

        @if (count($topics))
            @foreach ($topics as $topic)
                @include('pages.partials.topics_result')
            @endforeach
        @endif

        @if ((count($topics)+count($users)) <= 0)
            <div class="empty-block">{{ lang('Dont have any data Yet') }}~~</div>
        @endif

  </div>

  <div class="panel-footer">
      {!! $topics->appends(Request::except('page', '_pjax'))->render() !!}
  </div>
</div>

@stop


@section('scripts')

<script type="text/javascript">

    $(document).ready(function()
    {
        var query = '{{ $query }}';
        var results = query.match(/("[^"]+"|[^"\s]+)/g);
        results.forEach(function(entry) {
            $('.search-results').highlight(entry);
        });
    });

</script>
@stop

resources/views/pages/wiki.blade.php
@extends('layouts.default')

@section('title')
{{ lang('Community Wiki') }}_@parent
@stop

@section('content')

<div class="{{ count($topics) > 14 ?: 'col-md-6 col-md-offset-3' }} remove-padding-vertically" >

  <div class="panel panel-default">

    <div class="panel-heading">
      <h3 class="panel-title text-center">{{ lang('Community Wiki') }}</h3>
    </div>

    <div class="panel-body remove-padding-vertically remove-padding-horizontal">

    @if (count($topics))
      <div class="list-group">
        @foreach ($topics as $topic)
          <a class="list-group-item {{ count($topics) <= 14 ?: 'col-md-6' }}" href="{{ $topic->link() }}" title="{{{ $topic->title }}}">
            {{{ str_limit($topic->title, '100') }}}
          </a>
        @endforeach
      </div>
    @else
      <div class="empty-block">{{ lang('Dont have any data Yet') }}~~</div>
    @endif

    </div>

  </div>

</div>


@stop